bilby_pipe injection_study_bilby_pipe.ini --duration 8.0 --generation-seed 0 --injection-numbers 0 --label inj0 --outdir outdir_injections 
bilby_pipe injection_study_bilby_pipe.ini --duration 4.0 --generation-seed 1 --injection-numbers 1 --label inj1 --outdir outdir_injections 
bilby_pipe injection_study_bilby_pipe.ini --duration 4.0 --generation-seed 2 --injection-numbers 2 --label inj2 --outdir outdir_injections 
bilby_pipe injection_study_bilby_pipe.ini --duration 4.0 --generation-seed 3 --injection-numbers 3 --label inj3 --outdir outdir_injections 
bilby_pipe injection_study_bilby_pipe.ini --duration 4.0 --generation-seed 4 --injection-numbers 4 --label inj4 --outdir outdir_injections 
bilby_pipe injection_study_bilby_pipe.ini --duration 4.0 --generation-seed 5 --injection-numbers 5 --label inj5 --outdir outdir_injections 
bilby_pipe injection_study_bilby_pipe.ini --duration 4.0 --generation-seed 6 --injection-numbers 6 --label inj6 --outdir outdir_injections 
bilby_pipe injection_study_bilby_pipe.ini --duration 4.0 --generation-seed 7 --injection-numbers 7 --label inj7 --outdir outdir_injections 
bilby_pipe injection_study_bilby_pipe.ini --duration 4.0 --generation-seed 8 --injection-numbers 8 --label inj8 --outdir outdir_injections 
bilby_pipe injection_study_bilby_pipe.ini --duration 4.0 --generation-seed 9 --injection-numbers 9 --label inj9 --outdir outdir_injections 
